version: "3"

services:
   app:
      build:
         context:
         dockerfile: Dockerfile
      container_name: travel-app
      ports:
         - "3000:3000"
      env_file:
         - ./.env
      depends_on:
         - db
      networks:
         - backend
      volumes:
         - ./src:/back/src
   db:
      image: mysql:8.0
      container_name: mysql-db
      environment:
         MYSQL_ROOT_PASSWORD: ${PASSWORD}
         MYSQL_DATABASE: ${DATABASE}
         TZ: Asia/Seoul
         LANG: C.UTF-8
      ports:
         - "3306:3306"
      networks:
         - backend
      volumes:
         - mysql_data:/var/lib/mysql
   nginx:
      restart: unless-stopped
      container_name: nginx-server
      build:
         context: .
         dockerfile: Dockerfile.nginx
      volumes:
         - ./nginx.conf:/etc/nginx/nginx.conf
      ports:
         - "80:80"
      depends_on:
         - db
         - app
      networks:
         - backend
   gitlab-runner:
      image: gitlab/gitlab-runner:latest
      container_name: gitlab-runner
      restart: always
      volumes:
         - ./config/gitlab-runner:/etc/gitlab-runner
         - /var/run/docker.sock:/var/run/docker.sock
volumes:
   mysql_data:
networks:
   backend:
      driver: bridge
